"""OpenAI-compatible LLM client."""

from __future__ import annotations

import logging
import os
import time
from dataclasses import dataclass
from typing import Any

import httpx

from xyfrag.config import LLMConfig
from xyfrag.schemas import RetrievedDocument
from xyfrag.text import tokenize

logger = logging.getLogger(__name__)


class LLMClientError(RuntimeError):
    """Raised when the LLM provider call fails."""


@dataclass(frozen=True)
class LLMResponse:
    """LLM response payload.

    Args:
        content: Text content generated by the model.
        elapsed_seconds: Provider latency in seconds.
    """

    content: str
    elapsed_seconds: float


class OpenAICompatibleClient:
    """Minimal OpenAI-compatible chat completions client."""

    def __init__(self, config: LLMConfig) -> None:
        """Initialize the client.

        Args:
            config: LLM provider configuration.

        Returns:
            None.
        """

        self._config = config
        self._api_key = os.getenv("OPENAI_API_KEY", "")
        self._base_url = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1")

    async def chat(self, messages: list[dict[str, str]]) -> LLMResponse:
        """Call the chat completions endpoint.

        Args:
            messages: OpenAI-compatible chat messages.

        Returns:
            LLM response content and latency.

        Raises:
            LLMClientError: If the API key is missing, request fails, or response
                structure is invalid.
        """

        api_key = os.getenv("OPENAI_API_KEY", self._api_key)
        base_url = os.getenv("OPENAI_BASE_URL", self._base_url)
        model = os.getenv("OPENAI_MODEL", self._config.model)

        if not api_key:
            raise LLMClientError("OPENAI_API_KEY is not configured")

        payload: dict[str, Any] = {
            "model": model,
            "messages": messages,
            "temperature": self._config.temperature,
            "max_tokens": self._config.max_tokens,
        }
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }
        url = f"{base_url.rstrip('/')}/chat/completions"
        started_at = time.perf_counter()

        try:
            async with httpx.AsyncClient(timeout=self._config.timeout_seconds) as client:
                response = await client.post(url, headers=headers, json=payload)
                response.raise_for_status()
        except httpx.TimeoutException as exc:
            logger.error("LLM request timed out: %s", exc)
            raise LLMClientError("大模型请求超时，请稍后重试。") from exc
        except httpx.HTTPStatusError as exc:
            logger.error(
                "LLM HTTP error status=%s body=%s",
                exc.response.status_code,
                exc.response.text[:500],
            )
            raise LLMClientError("大模型服务返回异常，请检查配置或稍后重试。") from exc
        except httpx.RequestError as exc:
            logger.error("LLM network error: %s", exc)
            raise LLMClientError("大模型网络连接失败，请检查网络或服务地址。") from exc

        elapsed_seconds = time.perf_counter() - started_at
        data = response.json()
        try:
            content = str(data["choices"][0]["message"]["content"]).strip()
        except (KeyError, IndexError, TypeError) as exc:
            logger.error("Invalid LLM response structure: %s", data)
            raise LLMClientError("大模型响应格式异常。") from exc

        logger.info("LLM call completed elapsed=%.3fs", elapsed_seconds)
        return LLMResponse(content=content, elapsed_seconds=elapsed_seconds)


def build_mock_grounded_answer(query: str, documents: list[RetrievedDocument]) -> str:
    """Build a local extractive answer when no LLM key is configured.

    Args:
        query: User question.
        documents: Reranked source documents.

    Returns:
        A short citation-bearing answer grounded in the top source.
    """

    if not documents:
        return "资料库中未找到相关规定。"

    query_tokens = set(tokenize(query))
    best_sentence = ""
    best_source_index = documents[0].source_index
    best_score = -1

    for document in documents:
        sentences = _split_answer_sentences(document.chunk.text)
        for sentence in sentences:
            sentence_tokens = set(tokenize(sentence))
            score = _score_candidate_sentence(query, sentence, query_tokens)
            if score > best_score:
                best_score = score
                best_sentence = sentence
                best_source_index = document.source_index

    if not best_sentence:
        best_sentence = documents[0].chunk.text[:120].strip()

    if best_sentence.endswith("。"):
        return f"{best_sentence}[{best_source_index}]"
    return f"{best_sentence}。[{best_source_index}]"


def _split_answer_sentences(text: str) -> list[str]:
    """Split reference text into answerable sentence candidates.

    Args:
        text: Reference text.

    Returns:
        Clean sentence candidates.
    """

    sentences = []
    for sentence in text.replace("。", "。\n").splitlines():
        stripped = sentence.strip()
        if stripped and not stripped.startswith("#"):
            sentences.append(stripped)
    return sentences


def _score_candidate_sentence(
    query: str,
    sentence: str,
    query_tokens: set[str],
) -> float:
    """Score a local answer candidate sentence.

    Args:
        query: User question.
        sentence: Candidate sentence from retrieved references.
        query_tokens: Token set for the query.

    Returns:
        Candidate relevance score.
    """

    sentence_tokens = set(tokenize(sentence))
    score = float(len(query_tokens & sentence_tokens))

    if len(sentence) < 10:
        score -= 2.0

    asks_time = any(keyword in query for keyword in ("什么时候", "时间", "日期", "截止"))
    has_time_signal = any(
        keyword in sentence
        for keyword in ("开学", "工作日", "周", "天", "月", "日", "前", "后")
    )
    if asks_time and has_time_signal:
        score += 2.0

    return score
